/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Helper function to check if multi-core execution is available */
export declare function isMulticoreAvailable(): boolean
/** Get system information */
export declare function getMulticoreInfo(): string
/** Multi-core executor with enhanced JavaScript simulation */
export declare class MultiCoreExecutor {
  /** Create a new multi-core executor */
  constructor(workerCount?: number | undefined | null)
  /** Get the number of worker threads */
  get workerCount(): number
  /** Submit a task for parallel execution */
  submitTask(functionCode: string, data: string, timeoutMs?: number | undefined | null): string
  /** Submit multiple tasks for parallel execution across all cores */
  submitBatch(tasks: Array<[string, string]>): Array<string>
  /** Get result from completed task (blocking) */
  getResult(timeoutMs?: number | undefined | null): string
  /** Get all results for a batch (blocking until all complete) */
  getBatchResults(taskCount: number, timeoutMs?: number | undefined | null): Array<string>
  /** Shutdown the worker pool */
  shutdown(): void
}
