/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Task data structure for communication with JavaScript */
export interface TaskData {
  id: string
  functionString: string
  data: string
  timeout?: number
}
/** Helper function to check if Rust backend is available */
export declare function isRustAvailable(): boolean
/** Get system information */
export declare function getSystemInfo(): string
/** Simple synchronous threader for testing */
export declare class SimpleThreader {
  /** Create a new SimpleThreader instance */
  constructor()
  /** Execute a simple task synchronously (for testing) */
  executeSimple(functionString: string, data: string): string
  /** Execute multiple tasks synchronously */
  executeAllSync(tasks: Array<TaskData>): Array<string>
  /** Get the number of available CPU cores */
  get cpuCount(): number
}
